--- 
- hosts: all
  tasks: 
    - name: directory creation 
      file: path=/var/tmp/thinknyxdir mode=0744 state=directory
    - name: file creation
      file: path=/var/tmp/thinknyxdir/x1 mode=0777 state=touch 
